server:
    port: 8080
    forward-headers-strategy: framework
    error:
        include-exception: true
        include-stacktrace: never

spring:
    datasource:
        url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_DATABASE}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driverClassName: org.postgresql.Driver
    datasource.hikari:
        maximum-pool-size: 4
        idle-timeout: 10000
        max-lifetime: 60000

management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: 'health,prometheus,metrics,jolokia,info'
            cors:
                allowed-methods: GET

flyway:
    enabled: true
    datasources:
        default:
            enabled: true
            locations:
                - classpath:db/migration
            baseline-on-migrate: true
            check-location: true
            sql-migration-prefix: V
            repeatable-sql-migration-prefix: R
            sql-migration-separator: __
            sql-migration-suffixes: .sql